name: Deploy to Server

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore private.pem from secret
        run: |
          mkdir -p src/main/resources/keys
          echo "$PRIVATE_PEM" > src/main/resources/keys/private.pem
        env:
          PRIVATE_PEM: ${{ secrets.PRIVATE_PEM }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t soonrimi-be:latest . --load
          docker save soonrimi-be:latest > soonrimi-be.tar

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "soonrimi-be.tar,docker-compose.yml,src/main/resources/keys/private.pem"
          target: "/home/${{ secrets.SERVER_USER }}/soonrimi-be/"

      - name: Create .env file on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/soonrimi-be
            cat > .env << EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            ADMIN_REGISTER_PASSWORD=${{ secrets.ADMIN_REGISTER_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/soonrimi-be

            # Docker 이미지 로드
            docker load < soonrimi-be.tar

            # 기존 컨테이너 중지 및 제거
            docker compose down || true

            # 새 컨테이너 시작
            docker compose up -d

            # 사용하지 않는 이미지 정리
            docker image prune -f

            # 상태 확인
            sleep 10
            docker compose ps
